### ISSUE TITLE
User Management in OpenSwitch image will change

### ISSUE THREAD

**Issue by loaizara** [HPENetworking/topology_docker#13]
On February 17, will be changes that affect the root account in the OPS image, this change could be broke functionality. Read the threat above.

http://lists.openswitch.net/pipermail/ops-dev/2016-February/001752.html

**Comment by ocelotl** [comment]
@loaizara, thanks for the heads up. Closing this now since this is not an issue but a foreseen change. Please redirect further information like this one to topology_board@hpe.com
