### ISSUE TITLE
The openswitch node should stop vtysh gracefully

### ISSUE THREAD

**Issue by walintonc** [HPENetworking/topology_docker#15]
It looks like today after having processed all vtysh commands, the vtysh session isn't ended properly (i.e with 'exit').

I am trying to measure code coverage (gcov) and need the vtysh binary to gracefully end after having executed all my tests.

**Comment by walintonc** [comment]
Can i help you get this done?

**Comment by ocelotl** [comment]
I certainly do, @carlos-jenkins. I'll contact you to see how can you help us with this @walintonc, thanks a lot.

**Comment by ocelotl** [comment]
This issue is to be migrated when #18 is completed.
