### ISSUE TITLE
Place node-specific code in separate repos

### ISSUE THREAD

**Issue by ocelotl** [HPENetworking/topology_docker#18]
The implementation of nodes for this platform engine resides in this very same repo, they should be moved to completely separate the node development from this.

**Comment by keinohguchi** [comment]
Hi @ocelotl and team,

I'm coming from #9, it seems depends on this bug, and the state of this issue is still
open.  Just want to know if this is blocking #9 or we can work concurrently…

Just double check with you, as I have a specific question on #9.

Cheers,

Kei

**Comment by keinohguchi** [comment]
By the way, I've left a message on #9, [here](https://github.com/HPENetworking/topology_docker/issues/9#issuecomment-194561171).

Again, awesome job, team topology!
