### ISSUE TITLE
Need the openswitch.py node to accept a configurable parameter to start docker with an extra volume

### ISSUE THREAD

**Issue by walintonc** [HPENetworking/topology_docker#21]
RIght now the openswitch.py node is hardcoded to use the following volumes:

openswitch.py,

```python
         # Add binded directories
         binds = [
             '{}:/tmp'.format(shared_dir),
             '/dev/log:/dev/log',
             '/sys/fs/cgroup:/sys/fs/cgroup:ro'
         ]
```
I am working in adding code coverage support and as a  requirement I need to pass an extra bind (volume) to Docker and it needs to be programatically (it cant be hardcoded).

Using an environment variable is an option. For example, before calling tox I'd like to set the following variable

```
export VSI_COV_DATA_DIR=/some/location/for/coverage
```

and then after calling tox, this should result in something similar to:

```python
         # Add binded directories
         binds = [
             '{}:/tmp'.format(shared_dir),
             '/dev/log:/dev/log',
             '/sys/fs/cgroup:/sys/fs/cgroup:ro'
             '/some/location/for/coverage:/some/location/for/coverage'
         ]
```

It must be read/write.

Thanks

**Comment by ocelotl** [comment]
This *could* be implemented in some way using attribute injection, it would need this platform engine to recognize this attribute (``binds``, maybe?) and making it pass it to the specified node who'll have to handle it properly, or something like it, right? Well, maybe... ideas are welcome now gentlemen!

**Comment by walintonc** [comment]
In order to make it simple, can you just have the code detect the variable and add a new items to the binds list?

**Comment by ocelotl** [comment]
You mean the *environment* variable?

**Comment by dajose22** [comment]
:+1: to @ocelotl idea, as it is the frameworks way of specifying attributes to a node

**Comment by walintonc** [comment]
hey guys, ok understood no envvar, attr injection it is! Good luck, please let me know when I can use this new sharp functionality :smiley:

**Comment by ocelotl** [comment]
Yes it is! take a look at this:

https://github.com/HPENetworking/topology_docker/blob/master/lib/topology_docker/platform.py#L71 

in that ``metadata`` attribute you'll find treasure to plunder (and injection-defined attributes too)!

**Comment by walintonc** [comment]
Hi, sounds good. I will give it a try.

**Comment by ocelotl** [comment]
Outstanding, @walintonc, let us know if you need any help.

**Comment by walintonc** [comment]
@carlos-jenkins, been busy and have not started Although I commited to having this completed by Friday (commited to Kuntal, the CIT manager) and so I will probably start working on this today or tomorrow.

**Comment by walintonc** [comment]
Hi All

So I was going to start working on this but before I want to make sure that you guys understand my requirement and that still the solution suggested is appropriate.

What I need is to be able to somehow inform the Docker Topo Framework that when starting an openswitch node, to add an extra bind.

Now this has to be done only on specific scenarios, so the Openswitch node will add the extra bind only on demand. Specifically when running coverage reports.

So, I need to be able to configure this on demand some how, as the directory to bind to is different on every run.

Using an env-var was an option as I could simply export a env-var and reference it from within the openswitch.py script. But this is an no-go for you. And I am ok with this.

So the other option left is (I suppose)  passing an argument to the script when calling pytest/tox (?).
I will calculate the directory when running the tests and before calling tox to execute the tests I need a way to send this "attribute" to the Openswitch node. Is this what you mean with attribute injection?

And will this be something similar to

tox -- -v /some/volume/

Does this make sense?

**Comment by walintonc** [comment]
@carlos-jenkins 
Thanks much for your help! I see the new_binds_attribute branch that implements the change!
@ocelotl tested it with an injection file and it worked!
