### ISSUE TITLE
Host node interfaces with numeric name

### ISSUE THREAD

**Issue by fonsecamau** [HPENetworking/topology_docker#41]
When running a test case using an interface of a host node type named with only numeric characters (e.g.: 1), it fails when trying to access that interface for configuration. For example:

Given the following node:

```
[type=host name="Host 1"] hs1
hs1:1
```

When test tries to configure the interface,

`hs1("ip link set 1 up")`

The following error appears:

> Cannot find device "1"

Although the interface is created correctly under the netns front_panel (Already verified with ip link show), the configuration fails with the message mentioned before.

**Comment by jeffesquivels** [comment]
We now have a different shell to execute commands directly on the new network namespace named "bash_front_panel", which is the easier way to do this, like this:

`hs1("ip link set 1 up", shell="bash_front_panel")`

You need to specify the shell explicitly because otherwise, "bash" will be used (it is the default).

Btw, this command is equivalent to doing this:

`hs1("ip netns exec front_panel ip link set 1 up")`

But hopefully it's more convenient.

**Comment by fonsecamau** [comment]
@jeffesquivels thanks for the explanation. Although, when I use hs1("ip link set if01 up"), for example, it works but when using numeric interfaces as mentioned before I encounter the error regardless of the shell you are talking about. Why does it passes with alphanumeric interfaces but with numeric ones it fails?

**Comment by jeffesquivels** [comment]
@fonsecamau hmm, that's weird, could you please provide the output of `hs1("ip link list")` and `hs1("ip link list", shell="bash_front_panel")` for both cases (when the iface name is "1" and when the iface name is "if01"), please?

**Comment by fonsecamau** [comment]
@jeffesquivels sorry for the delay, here's the information you requested plus the commands sent to work with the interface and its correct configuration.

With alphanumeric interface:
2016-08-09T09:41:16.418590 [hs1].send_command('ip link list', shell='bash') ::
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN mode DEFAULT group default
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
258: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP mode DEFAULT group default
    link/ether 02:42:ac:13:00:02 brd ff:ff:ff:ff:ff:ff
2016-08-09T09:41:17.282918 [hs1].send_command('ip link list', shell='bash_front_panel') ::
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN mode DEFAULT group default
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
260: if01: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN mode DEFAULT group default qlen 1000
    link/ether 22:e3:ec:74:55:27 brd ff:ff:ff:ff:ff:ff
2016-08-09T09:41:18.030704 [hs1].send_command('ip link set if01 up', shell='bash') ::

2016-08-09T09:41:18.087813 [hs1].send_command('ip addr add 192.168.0.2/24 dev if01', shell='bash') ::

2016-08-09T09:41:23.146922 [hs1].send_command('ping -c 7 192.168.0.1', shell='bash') ::
PING 192.168.0.1 (192.168.0.1) 56(84) bytes of data.
64 bytes from 192.168.0.1: icmp_seq=1 ttl=64 time=0.063 ms
64 bytes from 192.168.0.1: icmp_seq=2 ttl=64 time=0.071 ms
64 bytes from 192.168.0.1: icmp_seq=3 ttl=64 time=0.084 ms
64 bytes from 192.168.0.1: icmp_seq=4 ttl=64 time=0.065 ms
64 bytes from 192.168.0.1: icmp_seq=5 ttl=64 time=0.110 ms
64 bytes from 192.168.0.1: icmp_seq=6 ttl=64 time=0.069 ms
64 bytes from 192.168.0.1: icmp_seq=7 ttl=64 time=0.079 ms

--- 192.168.0.1 ping statistics ---
7 packets transmitted, 7 received, 0% packet loss, time 5998ms
rtt min/avg/max/mdev = 0.063/0.077/0.110/0.016 ms

With numeric interface:
2016-08-09T09:45:08.407032 [hs1].send_command('ip link list', shell='bash') ::
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN mode DEFAULT group default
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
266: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP mode DEFAULT group default
    link/ether 02:42:ac:13:00:02 brd ff:ff:ff:ff:ff:ff
2016-08-09T09:45:09.145536 [hs1].send_command('ip link list', shell='bash_front_panel') ::
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN mode DEFAULT group default
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
268: 1: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN mode DEFAULT group default qlen 1000
    link/ether 36:87:f3:f7:f9:d4 brd ff:ff:ff:ff:ff:ff
2016-08-09T09:45:09.883044 [hs1].send_command('ip link set 1 up', shell='bash') ::
Cannot find device "1"
2016-08-09T09:45:09.940239 [hs1].send_command('ip addr add 192.168.0.2/24 dev 1', shell='bash') ::
Cannot find device "1"
2016-08-09T09:45:14.998862 [hs1].send_command('ping -c 7 192.168.0.1', shell='bash') ::
PING 192.168.0.1 (192.168.0.1) 56(84) bytes of data.

--- 192.168.0.1 ping statistics ---
7 packets transmitted, 0 received, 100% packet loss, time 6048ms

**Comment by jeffesquivels** [comment]
When we tried to reproduce this problem with a different alphanumeric name ("such as abs01") instead of "if01" it started failing the same way it does when using "1" as interface name. Exploring further, it seems that "if01" worked because ip link uses it as an alias for the first interface it finds, this can be tested with ip link show easily:

```
$ ip link show if01
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN mode DEFAULT group default qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
```

So in this case, it's not that `ip link set if01` is actually working on the "if01" interface on another namespace, but in reality what it's doing is working on the first interface it finds in this namespace (most likely lo).
